### PR TITLE
md5sum: implement SM3 hash utility

### PR DESCRIPTION
**Pull request by jiazhang0**
This new hash computing tool is provided for SM3 hash algorithm.

### CODE REVIEW

**Comment by pixelb** [comment]
Thanks for the patch. It's best to discuss new commands/options at coreutils@gnu.org
(it's fine to reference this github pull request)

Given a new hash command goes to the global command name space we try to ensure it will be widely useful. A common first step for hash functions is to get them included in the lower level openssl project, which is usable as a library or command, and is the source of architecture specific optimizations that coreutils can reuse.

**Comment by jiazhang0** [comment]
@pixelb Is it allowed to implement sm3 in gnulib firstly before openssl? I mean I will implement sm3 in openssl later and hopefully coreutils can merge this PR.

**Comment by pixelb** [comment]
Well part of the reason for trying openssl first/also is that it would probably be more accepting given it's both a library and a command. If there wasn't sufficient interest there, then it would be unlikely to get merged to coreutils. TBH I'm not sure how commonly used this is, so it's worth discussing at coreutils@gnu.org at least. thanks

**Comment by jiazhang0** [comment]
Dropped. The formal review is in coreutils@gnu.org.

**Pull request closed without merging**
